<!DOCTYPE html>
<html ng-app lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Paginator - version 0.0.1</title>
    <link rel="stylesheet" href="<?php echo BASE_URL . 'libs/CSS&JS/bootstrap/version/5.1.3/dist/css/bootstrap.min.css'; ?>">
</head>
<body>
    <div class="container">        
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Usrname</th>
                    <th scope="col">Password</th>
                </tr>
            </thead>
            <tbody>
                <?php for($i = 0; $i < count($users); $i++): ?>
                <tr class="">
                    <th scope="row"><?php echo $i; ?></th>
                    <td><a href="<?php echo $users[$i]['Rfrnc']; ?>" target="_blank"><?php echo $users[$i]['Usrnm']; ?></a></td>
                    <td><?php echo $users[$i]['Psswrd']; ?></td>                
                </tr>
            <?php endfor; ?> 
            </tbody>
        </table>   
        <h2>Function <b>getPagination()</b></h2>
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <!-- <FIRST> -->
                <?php if($params['first']): ?>
                <li class="page-item">
                    <a class="page-link" href="?page=<?php echo $params['first']; ?>">First</a>
                </li>                
                <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">First</a>
                </li>                
                <?php endif; ?>
                <!-- <.FIRST> -->

                <!-- <PREVIOUS> -->
                <?php if($params['previous']): ?>
                <li class="page-item"><a class="page-link" href="?page=<?php echo $params['previous']; ?>">Previous</a></li>
                <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
                <?php endif; ?>
                <!-- <.PREVIOUS> -->

                <?php for($i = 1; $i <= $params['total']; $i++): ?>
                <?php if($params['current'] != $i): ?>
                <li class="page-item">
                    <a class="page-link" href="?page=<?php echo $i; ?>"><?php echo $i; ?></a>
                </li>
                <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1"><?php echo $i; ?></a>
                </li>
                <?php endif; ?>
                <?php endfor; ?>                

                <!-- <NEXT> -->
                <?php if($params['next']): ?>
                <li class="page-item">
                    <a class="page-link" href="?page=<?php echo $params['next']; ?>">Next</a>
                </li>                
                <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Next</a>
                </li>                
                <?php endif; ?>
                <!-- <.NEXT> -->

                <!-- <LAST> -->
                <?php if($params['last']): ?>
                <li class="page-item">
                    <a class="page-link" href="?page=<?php echo $params['last']; ?>">Last</a>
                </li>                
                <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Last</a>
                </li>                
                <?php endif; ?>
                <!-- <.LAST> -->
            </ul>
        </nav>

        <h2>Function <b>getRangePagination()</b></h2>
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <!-- <FIRST> -->
                <?php if($params['first']): ?>
                <li class="page-item">
                    <a class="page-link" href="?page=<?php echo $params['first']; ?>">First</a>
                </li>                
                <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">First</a>
                </li>                
                <?php endif; ?>
                <!-- <.FIRST> -->

                <!-- <PREVIOUS> -->
                <?php if($params['previous']): ?>
                <li class="page-item"><a class="page-link" href="?page=<?php echo $params['previous']; ?>">Previous</a></li>
                <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
                <?php endif; ?>
                <!-- <.PREVIOUS> -->                

                <?php for($i = 0; $i <= count($paramsRange['range']); $i++): ?>
                <?php if($paramsRange['current'] != $paramsRange['range'][$i]): ?>
                <li class="page-item">
                    <a class="page-link" href="?page=<?php echo $paramsRange['range'][$i]; ?>"><?php echo $paramsRange['range'][$i]; ?></a>
                </li>
                <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1"><?php echo $paramsRange['range'][$i]; ?></a>
                </li>
                <?php endif; ?>
                <?php endfor; ?>

                <!-- <NEXT> -->
                <?php if($params['next']): ?>
                <li class="page-item">
                    <a class="page-link" href="?page=<?php echo $params['next']; ?>">Next</a>
                </li>                
                <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Next</a>
                </li>                
                <?php endif; ?>
                <!-- <.NEXT> -->

                <!-- <LAST> -->
                <?php if($params['last']): ?>
                <li class="page-item">
                    <a class="page-link" href="?page=<?php echo $params['last']; ?>">Last</a>
                </li>                
                <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Last</a>
                </li>                
                <?php endif; ?>
                <!-- <.LAST> -->
            </ul>
        </nav>
    </div>    
    <script src="<?php echo BASE_URL . 'libs/JS/angular.js/version/1.8.2/angular.js'; ?>"></script>
</body>
</html>